// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cluster} from '../models';
import {k8s} from '../models';

export function AddCluster(arg1:cluster.AddClusterInput):Promise<cluster.Cluster>;

export function AddNamespace(arg1:string,arg2:string):Promise<Array<string>>;

export function CloseExec(arg1:string):Promise<void>;

export function GetContexts(arg1:string):Promise<Array<cluster.KubeContext>>;

export function GetDeployment(arg1:string,arg2:string,arg3:string):Promise<k8s.DeploymentDetail>;

export function GetDeploymentYAML(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetPod(arg1:string,arg2:string,arg3:string):Promise<k8s.PodDetail>;

export function GetPodYAML(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetVersion():Promise<Record<string, string>>;

export function Health():Promise<string>;

export function ImportLocalCluster(arg1:string,arg2:string,arg3:string):Promise<cluster.Cluster>;

export function ListClusters():Promise<Array<cluster.Cluster>>;

export function ListCronJobs(arg1:string,arg2:string):Promise<Array<k8s.CronJobInfo>>;

export function ListDaemonSets(arg1:string,arg2:string):Promise<Array<k8s.WorkloadInfo>>;

export function ListDeploymentPods(arg1:string,arg2:string,arg3:string):Promise<Array<k8s.PodInfo>>;

export function ListDeployments(arg1:string,arg2:string):Promise<Array<k8s.WorkloadInfo>>;

export function ListEvents(arg1:string,arg2:string):Promise<Array<k8s.EventInfo>>;

export function ListIngresses(arg1:string,arg2:string):Promise<Array<k8s.IngressInfo>>;

export function ListJobs(arg1:string,arg2:string):Promise<Array<k8s.JobInfo>>;

export function ListLocalKubeconfigs():Promise<Array<cluster.LocalKubeconfig>>;

export function ListNamespaces(arg1:string):Promise<Array<k8s.NamespaceInfo>>;

export function ListNodes(arg1:string):Promise<Array<k8s.NodeInfo>>;

export function ListPods(arg1:string,arg2:string):Promise<Array<k8s.PodInfo>>;

export function ListSavedNamespaces(arg1:string):Promise<Array<string>>;

export function ListServices(arg1:string,arg2:string):Promise<Array<k8s.ServiceInfo>>;

export function ListStatefulSets(arg1:string,arg2:string):Promise<Array<k8s.WorkloadInfo>>;

export function OpenExternal(arg1:string):Promise<void>;

export function RemoveCluster(arg1:string):Promise<void>;

export function RemoveNamespace(arg1:string,arg2:string):Promise<Array<string>>;

export function ResizeExec(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StartDeploymentLogStream(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:boolean):Promise<string>;

export function StartExec(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function StartLogStream(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:boolean):Promise<string>;

export function StartPortForward(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function StopLogStream(arg1:string):Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function SwitchContext(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:string):Promise<cluster.ConnectionStatus>;

export function TestKubeconfig(arg1:string,arg2:string):Promise<cluster.ConnectionStatus>;

export function ValidateKubeconfig(arg1:string):Promise<cluster.KubeconfigInfo>;

export function WriteExec(arg1:string,arg2:string):Promise<void>;
