// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCluster(arg1) {
  return window['go']['main']['App']['AddCluster'](arg1);
}

export function GetContexts(arg1) {
  return window['go']['main']['App']['GetContexts'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ImportLocalCluster(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportLocalCluster'](arg1, arg2, arg3);
}

export function ListClusters() {
  return window['go']['main']['App']['ListClusters']();
}

export function ListLocalKubeconfigs() {
  return window['go']['main']['App']['ListLocalKubeconfigs']();
}

export function RemoveCluster(arg1) {
  return window['go']['main']['App']['RemoveCluster'](arg1);
}

export function SwitchContext(arg1, arg2) {
  return window['go']['main']['App']['SwitchContext'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestKubeconfig(arg1, arg2) {
  return window['go']['main']['App']['TestKubeconfig'](arg1, arg2);
}

export function ValidateKubeconfig(arg1) {
  return window['go']['main']['App']['ValidateKubeconfig'](arg1);
}
