// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCluster(arg1) {
  return window['go']['main']['App']['AddCluster'](arg1);
}

export function AddNamespace(arg1, arg2) {
  return window['go']['main']['App']['AddNamespace'](arg1, arg2);
}

export function CloseExec(arg1) {
  return window['go']['main']['App']['CloseExec'](arg1);
}

export function GetContexts(arg1) {
  return window['go']['main']['App']['GetContexts'](arg1);
}

export function GetPod(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPod'](arg1, arg2, arg3);
}

export function GetPodYAML(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPodYAML'](arg1, arg2, arg3);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ImportLocalCluster(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportLocalCluster'](arg1, arg2, arg3);
}

export function ListClusters() {
  return window['go']['main']['App']['ListClusters']();
}

export function ListCronJobs(arg1, arg2) {
  return window['go']['main']['App']['ListCronJobs'](arg1, arg2);
}

export function ListDaemonSets(arg1, arg2) {
  return window['go']['main']['App']['ListDaemonSets'](arg1, arg2);
}

export function ListDeployments(arg1, arg2) {
  return window['go']['main']['App']['ListDeployments'](arg1, arg2);
}

export function ListEvents(arg1, arg2) {
  return window['go']['main']['App']['ListEvents'](arg1, arg2);
}

export function ListIngresses(arg1, arg2) {
  return window['go']['main']['App']['ListIngresses'](arg1, arg2);
}

export function ListJobs(arg1, arg2) {
  return window['go']['main']['App']['ListJobs'](arg1, arg2);
}

export function ListLocalKubeconfigs() {
  return window['go']['main']['App']['ListLocalKubeconfigs']();
}

export function ListNamespaces(arg1) {
  return window['go']['main']['App']['ListNamespaces'](arg1);
}

export function ListNodes(arg1) {
  return window['go']['main']['App']['ListNodes'](arg1);
}

export function ListPods(arg1, arg2) {
  return window['go']['main']['App']['ListPods'](arg1, arg2);
}

export function ListSavedNamespaces(arg1) {
  return window['go']['main']['App']['ListSavedNamespaces'](arg1);
}

export function ListServices(arg1, arg2) {
  return window['go']['main']['App']['ListServices'](arg1, arg2);
}

export function ListStatefulSets(arg1, arg2) {
  return window['go']['main']['App']['ListStatefulSets'](arg1, arg2);
}

export function RemoveCluster(arg1) {
  return window['go']['main']['App']['RemoveCluster'](arg1);
}

export function RemoveNamespace(arg1, arg2) {
  return window['go']['main']['App']['RemoveNamespace'](arg1, arg2);
}

export function ResizeExec(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeExec'](arg1, arg2, arg3);
}

export function StartExec(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartExec'](arg1, arg2, arg3, arg4, arg5);
}

export function StartLogStream(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartLogStream'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartPortForward(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartPortForward'](arg1, arg2, arg3, arg4, arg5);
}

export function StopLogStream(arg1) {
  return window['go']['main']['App']['StopLogStream'](arg1);
}

export function StopPortForward(arg1) {
  return window['go']['main']['App']['StopPortForward'](arg1);
}

export function SwitchContext(arg1, arg2) {
  return window['go']['main']['App']['SwitchContext'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestKubeconfig(arg1, arg2) {
  return window['go']['main']['App']['TestKubeconfig'](arg1, arg2);
}

export function ValidateKubeconfig(arg1) {
  return window['go']['main']['App']['ValidateKubeconfig'](arg1);
}

export function WriteExec(arg1, arg2) {
  return window['go']['main']['App']['WriteExec'](arg1, arg2);
}
