// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cluster} from '../models';
import {k8s} from '../models';

export function AddCluster(arg1:cluster.AddClusterInput):Promise<cluster.Cluster>;

export function AddNamespace(arg1:string,arg2:string):Promise<Array<string>>;

export function GetContexts(arg1:string):Promise<Array<cluster.KubeContext>>;

export function GetVersion():Promise<Record<string, string>>;

export function Health():Promise<string>;

export function ImportLocalCluster(arg1:string,arg2:string,arg3:string):Promise<cluster.Cluster>;

export function ListClusters():Promise<Array<cluster.Cluster>>;

export function ListCronJobs(arg1:string,arg2:string):Promise<Array<k8s.CronJobInfo>>;

export function ListDaemonSets(arg1:string,arg2:string):Promise<Array<k8s.WorkloadInfo>>;

export function ListDeployments(arg1:string,arg2:string):Promise<Array<k8s.WorkloadInfo>>;

export function ListIngresses(arg1:string,arg2:string):Promise<Array<k8s.IngressInfo>>;

export function ListJobs(arg1:string,arg2:string):Promise<Array<k8s.JobInfo>>;

export function ListLocalKubeconfigs():Promise<Array<cluster.LocalKubeconfig>>;

export function ListNamespaces(arg1:string):Promise<Array<k8s.NamespaceInfo>>;

export function ListNodes(arg1:string):Promise<Array<k8s.NodeInfo>>;

export function ListPods(arg1:string,arg2:string):Promise<Array<k8s.PodInfo>>;

export function ListSavedNamespaces(arg1:string):Promise<Array<string>>;

export function ListServices(arg1:string,arg2:string):Promise<Array<k8s.ServiceInfo>>;

export function ListStatefulSets(arg1:string,arg2:string):Promise<Array<k8s.WorkloadInfo>>;

export function RemoveCluster(arg1:string):Promise<void>;

export function RemoveNamespace(arg1:string,arg2:string):Promise<Array<string>>;

export function SwitchContext(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:string):Promise<cluster.ConnectionStatus>;

export function TestKubeconfig(arg1:string,arg2:string):Promise<cluster.ConnectionStatus>;

export function ValidateKubeconfig(arg1:string):Promise<cluster.KubeconfigInfo>;
